language: node_js
node_js:
  - "7"

branches:
  only:
    - master

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "CELLIER Florian"
  - git config --local user.email "chadyred@gmail.com"
  - npm run release:patch:ci
deploy:
  - provider: script
    script: npm run release:patch
    api_key: $GITHUB_TOKEN
    file: ./*
    file_glob: true
    overwrite: true
