language: node_js
node_js:
  - "7"

branches:
  only:
    - changelog

script:
  # Set up git user name and tag this commit
  - git config --local user.name "CELLIER Florian"
  - git config --local user.email "chadyred@gmail.com"
  - npm run release:patch:ci
  - export TRAVIS_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
  - git branch
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_PULL_REQUEST
  - echo $TRAVIS_PULL_REQUEST_BRANCH
after_success:
  - if [ $TRAVIS_BRANCH == "changelog" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git push https://chadyred:${GITHUB_TOKEN}@github.com/chadyred/glpi-ocsinventory-stack-docker.git HEAD:master; fi
  - if [ $TRAVIS_BRANCH == "changelog" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git push https://chadyred:${GITHUB_TOKEN}@github.com/chadyred/glpi-ocsinventory-stack-docker.git --tags; fi
